### About Dataset

#### Context:
- In the United States, animal bites are often reported to law enforcement (such as animal control). The main concern with an animal bite is that the animal may be rabid. This dataset includes information on over 9,000 animal bites which occurred near Louisville, Kentucky from 1985 to 2017 and includes information on whether the animal was quarantined after the bite occurred and whether that animal was rabid.

#### Information each columns:
- bite_date: The date the bite occurred
- SpeciesIDDesc: The species of animal that did the biting
- BreedIDDesc: Breed (if known)
- GenderIDDesc: Gender (of the animal)
- color: color of the animal
- vaccination_yrs: how many years had passed since the last vaccination
- vaccination_date: the date of the last vaccination
- victim_zip: the zipcode of the victim
- AdvIssuedYNDesc: whether advice was issued
- WhereBittenIDDesc: Where on the body the victim was bitten
- quarantine_date: whether the animal was quarantined
- DispositionIDDesc: whether the animal was released from quarantine
- head_sent_date: the date the animalâ€™s head was sent to the lab
- release_date: the date the animal was released
- ResultsIDDesc: results from lab tests (for rabies)

#### Question 1

- a. Read the file Health_animalBites.csv and save it to the 'bites' variable dataframe.
- b. Convert data type (if any)
- c. How many 'bad line rows' in dataset
- d. How to deal with 'datetime' column with bad record

- visit https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html to set your 'error' parameters
- visit https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html to set your 'on_bad_lines' parameters

- use this structure to see what line are bad line:
- df = open("Health_AnimalBites.csv")
- row_count= len(df.readlines())

In [3]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np

In [6]:
bites = pd.read_csv('Health_AnimalBites.csv', on_bad_lines= 'warn')
bites

b'Skipping line 3: expected 15 fields, saw 16\nSkipping line 4: expected 15 fields, saw 16\nSkipping line 5: expected 15 fields, saw 16\nSkipping line 10: expected 15 fields, saw 18\nSkipping line 11: expected 15 fields, saw 18\nSkipping line 12: expected 15 fields, saw 19\n'

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1989-08-29 00:00:00,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
2,1989-11-24 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40211,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
3,1990-02-08 00:00:00,DOG,NaN,FEMALE,BLACK/WHIT,1.0,1990-02-13 00:00:00,40203,NO,BODY,1990-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1990-02-22 00:00:00,DOG,NaN,MALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,1990-02-23 00:00:00,RELEASED,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8992,2017-09-05 00:00:00,DOG,NaN,NaN,NaN,NaN,NaN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8993,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
8994,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8995,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
8996,2017-09-07 00:00:00,DOG,BOXER,NaN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

In [7]:
bites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8997 entries, 0 to 8996
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bite_date          8680 non-null   object
 1   SpeciesIDDesc      8879 non-null   object
 2   BreedIDDesc        3759 non-null   object
 3   GenderIDDesc       6471 non-null   object
 4   color              6421 non-null   object
 5   vaccination_yrs    3738 non-null   float64
 6   vaccination_date   4115 non-null   object
 7   victim_zip         7163 non-null   object
 8   AdvIssuedYNDesc    2559 non-null   object
 9   WhereBittenIDDesc  8381 non-null   object
 10  quarantine_date    2014 non-null   object
 11  DispositionIDDesc  1529 non-null   object
 12  head_sent_date     395 non-null    object
 13  release_date       1445 non-null   object
 14  ResultsIDDesc      1537 non-null   object
dtypes: float64(1), object(14)
memory usage: 1.0+ MB

In [16]:
f = open("Health_AnimalBites.csv")
row_count = len(f.readlines())
print(row_count)
df2 = pd.read_csv("Health_AnimalBites.csv", on_bad_lines= 'warn')
print('number of bad line rows', row_count - df2.shape[0])

9004
number of bad row 7

b'Skipping line 3: expected 15 fields, saw 16\nSkipping line 4: expected 15 fields, saw 16\nSkipping line 5: expected 15 fields, saw 16\nSkipping line 10: expected 15 fields, saw 18\nSkipping line 11: expected 15 fields, saw 18\nSkipping line 12: expected 15 fields, saw 19\n'

In [136]:
bites['bite_date'] = pd.to_datetime(bites['bite_date'], errors = 'coerce')
bites['head_sent_date']= pd.to_datetime(bites['head_sent_date'])
bites['release_date'] = pd.to_datetime(bites['release_date'])
bites['quarantine_date'] = pd.to_datetime(bites['quarantine_date'])
bites['release_date'] = pd.to_datetime(bites['release_date'])
bites['vaccination_date'] = pd.to_datetime(bites['vaccination_date'])
bites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8997 entries, 0 to 8996
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bite_date          8679 non-null   datetime64[ns]
 1   SpeciesIDDesc      8879 non-null   object
 2   BreedIDDesc        3759 non-null   object
 3   GenderIDDesc       6471 non-null   object
 4   color              6421 non-null   object
 5   vaccination_yrs    3738 non-null   float64
 6   vaccination_date   4115 non-null   datetime64[ns]
 7   victim_zip         7163 non-null   object
 8   AdvIssuedYNDesc    2559 non-null   object
 9   WhereBittenIDDesc  8381 non-null   object
 10  quarantine_date    2014 non-null   datetime64[ns]
 11  DispositionIDDesc  1529 non-null   object
 12  head_sent_date     395 non-null    datetime64[ns]
 13  release_date       1445 non-null   datetime64[ns]
 14  ResultsIDDesc      1537 non-null   object
dtypes: datetime64[ns](5), float64(1), object(9)
memory usage: 1.0+ MB

In [19]:
bites

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05,UNKNOWN,NaT,NaT,UNKNOWN
1,1989-08-29,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaT,UNKNOWN,NaT,NaT,UNKNOWN
2,1989-11-24,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40211,NO,BODY,NaT,UNKNOWN,NaT,NaT,UNKNOWN
3,1990-02-08,DOG,NaN,FEMALE,BLACK/WHIT,1.0,1990-02-13 00:00:00,40203,NO,BODY,1990-02-12,UNKNOWN,NaT,NaT,UNKNOWN
4,1990-02-22,DOG,NaN,MALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,1990-02-23,RELEASED,NaT,NaT,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8992,2017-09-05,DOG,NaN,NaN,NaN,NaN,NaN,40243,NaN,UNKNOWN,NaT,NaN,NaT,NaT,NaN
8993,2017-09-07,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaT,NaN,NaT,NaT,NaN
8994,2017-09-07,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaT,NaN,NaT,NaT,NaN
8995,2017-09-07,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaT,NaN,NaT,NaT,NaN
8996,2017-09-07,DOG,BOXER,NaN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaT,NaN,NaT,NaT,NaN

#### Question 2

- a. Filter out rows from DataFrame bites that have no NaN values in the SpeciesIDDesc and BreedIDDesc columns and save them in a new variable dataframe 'species'.
- b. What species are in DataFrame 'species'? How many varieties are there in each species?

In [24]:
species = bites.dropna(subset=['SpeciesIDDesc','BreedIDDesc'])
species

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
1147,2010-12-24,DOG,GERM SHEPHERD,UNKNOWN,BROWN/BLAC,NaN,NaN,40291,NO,BODY,2010-12-27,UNKNOWN,2010-12-26,NaT,NEGATIVE
1196,2011-01-11,DOG,DACHSHUND,MALE,RED,1.0,2010-02-12 00:00:00,40207,NO,BODY,2011-01-12,UNKNOWN,NaT,NaT,UNKNOWN
1202,2011-01-16,DOG,PIT BULL,UNKNOWN,BLK-WHITE,NaN,NaN,40216,NO,BODY,2011-01-18,KILLED,2011-01-16,NaT,NEGATIVE
1233,2011-01-28,DOG,GERM SHEPHERD,MALE,BLACK,NaN,NaN,40215,NO,NaN,2011-01-28,NaN,NaT,NaT,NaN
1238,2011-01-29,DOG,SHIH TZU,MALE,BEIGE-WHT,3.0,2010-07-26 00:00:00,40223,NO,BODY,2011-01-31,NaN,NaT,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8991,2017-09-06,DOG,CHICHAUHUA,FEMALE,TAN,NaN,NaN,40206,NaN,HEAD,NaT,NaN,NaT,NaT,NaN
8993,2017-09-07,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaT,NaN,NaT,NaT,NaN
8994,2017-09-07,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaT,NaN,NaT,NaT,NaN
8995,2017-09-07,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaT,NaN,NaT,NaT,NaN
8996,2017-09-07,DOG,BOXER,NaN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaT,NaN,NaT,NaT,NaN

In [64]:
unique_species = species['SpeciesIDDesc'].unique()
print('Species:', unique_species)
cat_unique_variety = species[species['SpeciesIDDesc'] == 'CAT']['BreedIDDesc'].nunique()
dog_unique_variety = species[species['SpeciesIDDesc'] == 'DOG']['BreedIDDesc'].nunique()
print(f'CAT: {cat_unique_variety}\nDOG: {dog_unique_variety}')

Species: ['DOG' 'CAT']
CAT: 2
DOG: 101

#### Question 3

- a. In DataFrame 'species', which dog breed is the most common?
- b. Of the dogs have black color, which breed is the most popular?

In [72]:
common_dog_breed = species[species['SpeciesIDDesc'] =='DOG']['BreedIDDesc'].value_counts()
common_dog_breed.sort_values(ascending= False).head(1)

PIT BULL    1101
Name: BreedIDDesc, dtype: int64

In [75]:
black_dog_breed = species[(species['SpeciesIDDesc'] == 'DOG')&(species['color'] == 'BLACK')]
black_dog_breed['BreedIDDesc'].value_counts().sort_values(ascending= False).head(1)

LABRADOR RETRIV    76
Name: BreedIDDesc, dtype: int64

#### Question 4

- a. Back to DataFrame 'bites', in 2015 how many data 'bites' were recorded?
- b. Of these 'bites', display those that are not confirmed to have been caused by dogs or cats.

In [90]:
bites_2015 = bites[bites['bite_date'].dt.year == 2015]
bites_2015

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
1407,2015-01-30,BAT,NaN,NaN,NaN,NaN,NaN,NaN,NO,UNKNOWN,NaT,NaN,2015-01-30,NaT,NEGATIVE
1408,2015-03-06,CAT,NaN,NaN,NaN,NaN,NaN,40214,NaN,BODY,NaT,NaN,2015-03-09,NaT,NEGATIVE
1409,2015-03-09,DOG,CHOW CHOW,NaN,NaN,NaN,NaN,NaN,NaN,BODY,NaT,NaN,2015-03-12,NaT,NEGATIVE
1410,2015-04-30,DOG,AAUST. TERR.,FEMALE,BROWN,NaN,NaN,40220,NO,BODY,NaT,KILLED,2015-04-30,NaT,NEGATIVE
1411,2015-05-04,CAT,NaN,FEMALE,TORTIE,NaN,NaN,40223,NaN,HEAD,NaT,NaN,2015-05-04,NaT,NEGATIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7164,2015-12-28,DOG,BORDER COLLIE,NaN,BLK,NaN,NaN,40511,NaN,BODY,NaT,NaN,NaT,2016-01-07,NaN
7165,2015-12-31,DOG,PIT BULL,MALE,BRN WHT,1.0,2016-01-14 00:00:00,40216,NaN,UNKNOWN,NaT,NaN,NaT,2016-01-11,NaN
7168,2015-01-06,DOG,PIT BULL,MALE,BRN WHT,NaN,NaN,40245,NaN,UNKNOWN,NaT,NaN,NaT,2016-01-19,NaN
7404,2015-03-31,DOG,ROTTWEILER,NaN,NaN,NaN,NaN,40243,NaN,BODY,NaT,NaN,NaT,NaT,NaN
7626,2015-06-02,DOG,NaN,NaN,NaN,NaN,NaN,40217,NaN,BODY,NaT,NaN,NaT,NaT,NaN

In [93]:
print('bite case in 2015:',bites_2015['bite_date'].count())

bite case in 2015: 985

In [100]:
print('unspecified species case in 2015:', bites_2015['SpeciesIDDesc'].isnull().sum())

unspecified species case in 2015: 7

#### Question 5

- a. List the bite sites in the data, excluding NaN and UNKNOWN values.
- b. Which animal has not been recorded to have bitten the victim's head?

In [109]:
bited = bites[(~bites['WhereBittenIDDesc'].isna() & (bites['WhereBittenIDDesc'] != 'UNKNOWN'))]
bited['WhereBittenIDDesc'].unique()

array(['BODY', 'HEAD'], dtype=object)

In [135]:
head_bited = bited[bited['WhereBittenIDDesc'].str.find('HEAD') != -1]
not_head_bited = bited[bited['WhereBittenIDDesc'].str.find('HEAD') == -1]
A = head_bited['SpeciesIDDesc'].unique()
B = not_head_bited['SpeciesIDDesc'].unique()
print('animal has not been recored',set(B)-set(A))

animal has not been recored {'RABBIT', 'FERRET', 'SKUNK', 'RACCOON'}

#### Question 6

- a. In the data, how many rabies-negative animals (NEGATIVE) were killed (KILLED) or died (DIED)?
- b. Between 2010 and 2015, calcuate what percentage of bites in the data cause by dogs?

In [137]:
negative = bites[bites['ResultsIDDesc'] == 'NEGATIVE']
killed_died_negative = negative[negative['DispositionIDDesc'].isin(['KILLED','DIED'])]
print('Number of rabies-negative animals were killed or died:', killed_died_negative.shape[0])

Number of rabies-negative animals were killed or died: 16

In [149]:
dog_2010_2015 = bites[(bites['bite_date'].dt.year >= 2010) & (bites['bite_date'].dt.year <= 2015)]
dog_5 = dog_2010_2015[dog_2010_2015['SpeciesIDDesc'] == 'DOG']
print('percentage of dog bites:', round(dog_5.shape[0]/dog_2010_2015.shape[0],2)*100)

percentage of dog bites: 79.0

#### Question 7

- a. Calculate the average number of vaccination years of the animals (excluding lines with NaN values in this column).
- b. How many attacks were there in 2017 in which the attacking animal was a BOXER dog?

In [154]:
print('Average number of vaccination years:', round(bites[bites['vaccination_yrs'].notna()]['vaccination_yrs'].mean(),2))

Average number of vaccination years: 1.45

In [160]:
boxer_2017 = bites[(bites['bite_date'].dt.year == 2017) & (bites['BreedIDDesc']=='BOXER')]
print('number of BOXER dog in 2017:',boxer_2017.shape[0])

number of BOXER dog in 2017: 33

#### Question 8

- a. How many animals were recorded on arrival in the laboratory?
- b. Of these animals, what percentage do dogs make up?

In [180]:
lab = bites[bites['head_sent_date'].notna()]
print('number of animal recorded in the laboratory:',lab.shape[0])

number of animal recorded in the laboratory: 395

In [182]:
dog_lab = lab[lab['SpeciesIDDesc'] =='DOG'].shape[0]
print('percentage of dog is:', round((dog_lab/lab.shape[0])*100,2))

percentage of dog is: 26.58

#### Question 9

- a. How many dogs have been recorded on release date?
- b. How many of them are recorded to have been vaccinated for at least 1 year?

In [185]:
released_bite = bites[bites['release_date'].notna()]
print('number of dog recorded on release date:', released_bite[released_bite['SpeciesIDDesc'] == 'DOG'].shape[0])

number of dog recorded on release date: 1249

In [192]:
vaccinated_dog = released_bite[(released_bite['SpeciesIDDesc'] == 'DOG') & (released_bite['vaccination_yrs'] >= 1)]
print('number of dog have vaccinated for at least 1 year:',vaccinated_dog.shape[0])

number of dog have vaccinated for at least 1 year: 943

#### Question 10

- In the years 2010 to 2016, which breed of species caused the most bites? Do not count rows with NaN or UNKNOWN values in these 2 columns.

In [195]:
bites_2010_2016 = bites[(bites['bite_date'].dt.year >= 2010) & (bites['bite_date'].dt.year <= 2016)]
bites_2010_2016 = bites_2010_2016[(bites_2010_2016['BreedIDDesc'].notna()) & (bites_2010_2016['SpeciesIDDesc'].notna())]

In [224]:
dog_2010_2016 = bites_2010_2016[bites_2010_2016['SpeciesIDDesc'] == 'DOG'].groupby('BreedIDDesc').size().sort_values(ascending= False)
print('most dog breed recorded between 2010 and 2016:',dog_2010_2016.head(1))

most dog breed recorded between 2010 and 2016: BreedIDDesc
PIT BULL    915
dtype: int64

In [230]:
cat_2010_2016 = bites_2010_2016[bites_2010_2016['SpeciesIDDesc'] == 'CAT'].groupby('BreedIDDesc').size().sort_values(ascending= False)
print('most dog breed recorded between 2010 and 2016:',cat_2010_2016.head(1))

most dog breed recorded between 2010 and 2016: BreedIDDesc
OTHER    1
dtype: int64